# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23d61546cf2fcfc752bf96fb5ce6ced60b484f0123b89df6bc97c33183937976b2614a2cee0f2c195baaa2a95078a1033010e858814f22a671074f55cc96698c

test:
  secret_key_base: 526d2fc9fed4ba2f8c0234d9c86a319c50b85e3c6da22b68e11fca3bbcb6b879684b7da92d01abbc1e25d8958f8011a44aefb6866159f24135ef9e01e13a452f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
